### ISSUE TITLE
프로젝트 역할 분담

### ISSUE THREAD

**Issue by choigowon** [cbnuLeehyunwoo/Fine_Dust_Measurment#1]
우리가 구현하고자 하는 주제에 맞게 3가지로 분류해봤습니다.
각자 원하는 역할과 그 이유를 적어주세요.

1. 사이트 만들기
2. 웹 스크래핑
3. 아두이노를 통한 미세먼지 측정

사실상 2, 3번을 빨리 끝내고 1번에 붙어야 할 것 같아 2, 3번을 먼저 끝내고 1번을 다같이 하는 방법도 있습니다.

**Comment by gihong-free** [comment]
제가 HTML, CSS기초 지식이 있어서 사이트 만들기를 하고 싶습니다. 하지만 정말 기초 지식이라 하루면 저 정도의 지식은 습득 가능하기에 원하는 사람이 있으면 다른 것도 가능합니다.
 추가로 사이트 구현에 있어서 웹 스크래핑 코드나 결과 데이터를 해석이나 현황 등을 알아야 사이트에 응용할 수 있어서, 웹 스크래핑하는 분과 잦은 협동이 필요해 보입니다! (ex: 어디서 웹 스크래핑을 할지 미리 알려주어야 사이트를 미리 제작 가능 등..)

**Comment by cbnuleehyunwoo** [comment]
이전에 아두이노 미세먼지 측정기를 만들어본 적이 있어서 제가 3번을 우선 맡아서 해보겠습니다.  아두이노와 컴퓨터간 시리얼 통신까지만 구현해봤기 때문에 통신 결과를 실시간으로 전달할 수 있는 방법에 대해 우선적으로 알아보고 구현할 생각입니다.

**Comment by choigowon** [comment]
BeautifulSoup4와 lxml을 이용하여 웹 스크래핑을 간단하게 나마 해본 적이 있어, 제가 웹 스크래핑을 맡는 걸로 하겠습니다.

+사이트를 포함하여 어디서, 어디까지 정보를 받아올 것인지는 추후 협의를 통해 진행하겠습니다.

**Comment by choigowon** [comment]
@gihong-free : 사이트
@cbnuLeehyunwoo : 아두이노
@choigowon : 스크래핑

어느 정도 코드 완성한 분들은 사이트 만들기에 붙는 걸로 하겠습니다.
