### ISSUE TITLE
master 브런치 merge 관련 이슈

### ISSUE THREAD

**Issue by gihong-free** [cbnuLeehyunwoo/Fine_Dust_Measurment#11]
각 지역의 html에 스크래핑해온 내용을 합치는 작업은 각자의 브런치를 master 브런치에 merge한 후에 작업하는 것이 conflict를 예방하는 방법이라고 생각합니다.
 곧 html에 스크래핑 내용과 아두이노를 이용한 미세먼지 측정 수치를 추가할 단계가 올 것 같은데, 그 전에 각자의 브런치를 merge하는 것이 좋아 보입니다.

**Comment by choigowon** [comment]
먼저 현재까지 각자 진행 상황과 남은 일정에 대해 올려주시면 감사하겠습니다.

**Comment by choigowon** [comment]
merge 완료했습니다!
