### ISSUE TITLE
웹 스크래핑 파일을 실행시키기 위한 조건

### ISSUE THREAD

**Issue by choigowon** [cbnuLeehyunwoo/Fine_Dust_Measurment#13]
웹 스크래핑 및 해당 내용을 html 문서로 전달하기 위해 (= 파일을 실행시키기 위해) 여러 라이브러리와 웹 프레임워크 설치가 필요합니다. 설치 방법은 다음과 같습니다.

**Comment by choigowon** [comment]
Beautiful Soup : 파이썬으로 웹 스크래핑하기 위해 제공되는 라이브러리입니다.
명령어
pip install beautifulsoup4

**Comment by choigowon** [comment]
Flask : 파이썬으로 Flask 웹 프레임워크를 통해 html 문서 작성 가능

설치 명령어
pip install Flask

**Comment by choigowon** [comment]
파이썬에서 해당 명령어가 작동하지 않는 경우 cmd에서 실행해보시기 바랍니다.

이외에 작동되지 않는 경우가 생기면 comment 달아주시기 바랍니다.

**Comment by cbnuleehyunwoo** [comment]
requests 모듈도 pip install requests로 설치 해야할 것 같습니다.

**Comment by cbnuleehyunwoo** [comment]
lxml 모듈이 안깔려있다면 깔아야할 것 같습니다
pip install lxml
