### ISSUE TITLE
새로운 환경에서 웹사이트 구동 시 이미지 깨지는 버그

### ISSUE THREAD

**Issue by cbnuleehyunwoo** [cbnuLeehyunwoo/Fine_Dust_Measurment#16]
제 노트북에서 웹사이트를 실행하려고 하였는데 이미지가 깨지는 버그가 발생했습니다
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/85469621/1546c39c-51ff-42ed-ba04-2b7739cc5fcc)
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/85469621/e1266bf8-db43-4488-9e81-413900066c9e)

![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/85469621/b61da024-ed73-4047-8d49-dc98770eb1c5)
현재 보시는 것처럼 이미지는 templates 폴더에 넣어둔 상태이고 파이썬 모듈도 다 설치해두었습니다. 
실행환경은 VS 코드로 실행하였습니다.

해당 문제의 해결방안을 아시는 분은 알려주시면 감사하겠습니다.

**Comment by gihong-free** [comment]
각 지역들의 html과 이미지들을 visual studio code의 하나의 파일에 넣어둔 후에 진행하면 정상적으로 진행될 것입니다.

**Comment by choigowon** [comment]
아직 파이썬과 html을 제대로 연결하지 않은 상태라 일부 이미지는 아직 첨부하지 못했습니다.

또한 이미지 위치를 다른 파일로 옮겨야 해서 main branch의 파일 위치 수정 후 다시 작성하겠습니다.

**Comment by choigowon** [comment]
파일 위치를 옮겼습니다. html 코드만 바꾸면 정상적으로 이미지가 첨부될 것 같습니다.

**Comment by gihong-free** [comment]
고생하셨습니다. 나머지 부분은 직접 만나서 논의하면 좋을 것 같습니다.
