### ISSUE TITLE
스크랩 할 미세먼지 사이트

### ISSUE THREAD

**Issue by choigowon** [cbnuLeehyunwoo/Fine_Dust_Measurment#2]
미세먼지 사이트 어떤 사이트에서 스크래핑 해올 지 추천 받습니다.

**Comment by choigowon** [comment]
에어코리아
네이버 날씨
웨더아이

**Comment by choigowon** [comment]
+ 색칠로만 알려주는 곳 보다는 미세먼지 값까지 알려주는 곳이면 좋겠습니다.

**Comment by gihong-free** [comment]
aqicn.org 한번 참고하시면 좋을 것 같습니다.

**Comment by cbnuleehyunwoo** [comment]
충북보건환경연구원에서 업데이트하는 미세먼지 정보를 참고해도 좋을 것 같습니다. 
https://www.chungbuk.go.kr/here/srmmr/list.do?key=1858

**Comment by choigowon** [comment]
현재 '네이버'와 '충북보건환경연구원' 사이트에서는 문제 없이 웹 스크래핑이 가능합니다.

'웨더아이'는 한글이 깨지는 문제
'에어코리아'와 'aqicn'는 도시를 특정하기가 힘든 문제로 (= 실력의 문제로) 현재 스크래핑 해올 수가 없습니다.

일단 최대한 되는 데까지 해보겠지만, 계속해서 다양한 사이트 추천해주시면 감사하겠습니다.

**Comment by choigowon** [comment]
웨더아이 문제 해결
