### ISSUE TITLE
앞으로의 작업 방식

### ISSUE THREAD

**Issue by choigowon** [cbnuLeehyunwoo/Fine_Dust_Measurment#21]
웹 스크래핑, 아두이노 branch에서 최소한의 기능을 구현할 수 있는 상황이라 merge한 상태입니다.
앞으로는 사이트 branch를 위주로 작업해야 할 것 같습니다.

이 하나의 branch를 3명이서 어떻게 나눠서 작업할 지 comment 달아주시면 감사하겠습니다.

**Comment by choigowon** [comment]
첫 번째로 사이트 branch에서 3명 각각의 branch를 만들어 작업하는 방식이 있습니다.

**Comment by gihong-free** [comment]
제 생각에는 고원님의 의견대로 사이트 branch에서 각자 branch를 만들어서 작업을 하고, 추가로 작업을 하기 전에 이슈를 통해 구현하고자 하는 것을 먼저 말해서 겹치지 않게 하는 것이 좋을 것 같습니다.
정리 : 이슈로 구현할 것 보고 후 각자 브런치에서 구현 후 pull request 요청

**Comment by cbnuleehyunwoo** [comment]
서로 작업반경이 겹치면 충돌이 발생할 수 있기에 고원님의 의견이 좋은 것 같습니다
