### ISSUE TITLE
html 참고 사이트

### ISSUE THREAD

**Issue by gihong-free** [cbnuLeehyunwoo/Fine_Dust_Measurment#22]
앞으로는 html을 꾸미는 작업들을 하게 될 것입니다. 
html과 css, javascript는 다들 처음 사용할 것이라 생각되어 간단하게 정리되어 있는 사이트를 추천해주려고 합니다.
https://www.opentutorials.org/course/3083 생활코딩이라는 이 사이트의 web 파트에서 html, css에 대한 강의를 참고한다면 많은 도움이 될 것이라 생각합니다.

**Comment by cbnuleehyunwoo** [comment]
감사합니다, 참고하도록 하겠습니다.
