### ISSUE TITLE
파이썬에서 Flask 모듈을 사용하여 html 불러올 때 이미지와 html링크가 제대로 작동하지 않는 버그

### ISSUE THREAD

**Issue by cbnuleehyunwoo** [cbnuLeehyunwoo/Fine_Dust_Measurment#23]
새로운 개발환경에서 웹페이지 스크래핑 코드를 실행할 때 404 에러가 발생하며 코드 내의 html, 이미지의 링크가 작동하지 않는 버그가 있었습니다.
![오류 3](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/85469621/1ff8ff43-3a46-4d1f-a843-044bca6c87e7)
지속적으로 문제해결을 시도해본 결과 Flask 모듈을 이용해 html을 사용할 때 반드시 지켜야하는 것들이 있었습니다.
1.  html파일은 templates 폴더를 생성하여 저장.
2.  css, js 이미지, 동영상 등의 파일은 static 폴더를 생성하여 저장.

├── scr.py
├── static 
│   │
│   ├── image
│   └── css
│       └── test.css
└── templates
    └── site.html
    반드시 해당 모양처럼 디렉토리를 구성해야 합니다.
3. url_for 함수 사용.
다행히 1번과 2번은 고원님이 해결을 해주셨기 때문에, 3번을 해결하였습니다.

해결방법
1.  html에서 기존의 링크를 생성하는 방식인
`<a href="Cheongju.html"></a>` 의 방식에서
`<a href="{{url_for('cheongju')}}"> </a>`의 방식을 사용

2. url_for 함수에게 전달할 문자열
 scr.py에서 app.route로선언한 함수명 ~~~ (def ~~~) 을 사용.

**Comment by choigowon** [comment]
파이썬 파일에 photo1 = f"img/Whetheri.jpg"
html에 <div><img src={{url_for("static", filename = photo1)}}></div>
입력하면 사진이 정상적으로 나올 것입니다.

**Comment by choigowon** [comment]
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/154347680/4e157e19-7471-430c-99ee-9bdd50b20acc)
