### ISSUE TITLE
미세먼지 페이지에 들어갈 사진 구하기

### ISSUE THREAD

**Issue by cbnuleehyunwoo** [cbnuLeehyunwoo/Fine_Dust_Measurment#25]
미세먼지 페이지를 구현할 때 각각의 상황에 맞게 넣을 사진을 여기에 미리 모아두면 좋을 것 같습니다. 

1. 환기 가능, 불가능

2. 조깅 가능 불가능

3. 마스크 쓰기, 마스크 안써도 ok

4. 물, 야채 많이먹기

5. 외출 가능, 자제

환기 가능
![환기 가능](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/85469621/1454fb44-0957-4dc9-83c4-45f22fe9e7eb)

환기 불가능
![환기 불가능](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/85469621/913553fa-b30e-43e0-bd6e-43d8ddee1488)

조깅 불가능
![조깅 불가능](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/85469621/892436cc-ed80-4d5e-934a-cdaadc2afed5)

**Comment by choigowon** [comment]
각 행동마다 사진을 넣게 되면 공간을 많이 차지할 것 같아 사진을 얼마나 넣어야 할지도 정해야 할 것 같습니다.
