### ISSUE TITLE
이미지 첨부 방법

### ISSUE THREAD

**Issue by choigowon** [cbnuLeehyunwoo/Fine_Dust_Measurment#26]
현재 이미지 첨부를 다운받은 이미지를 첨부하여 사이트를 작성하고 있습니다.
html만 사용한다면 문제가 없지만 현재 flask를 이용하여 python과 html을 연동해서 작성하다보니 다운받은 이미지를 첨부하려고 하면 다소 복잡해집니다.
현재 우리는 static 파일 안 img 파일 안에 이미지를 두어 파이썬에서 이미지 경로를 지정한다음 html로 보내 html에서 받아와서 이미지를 띄우는 형식이다 보니 코드가 다소 길어지기도 하고, 백그라운드 이미지를 넣는 데 어려움이 있습니다.
하지만 이미지 주소를 이용하면 위와 같은 과정이 필요없으므로 코드의 길이나 복잡성 면에서 더 간결해집니다.

- 현재 이미지 첨부 방법
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/154347680/aa5ca755-000a-4c32-b8fa-5efcb545f2ac)
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/154347680/e315f17a-e33d-4907-a300-91aa33430285)
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/154347680/043f95b9-e09e-4891-90db-6850a9ba33ca)

**정리하자면 다운받은 이미지를 첨부하는 것이 아닌 이미지 주소를 이용하여 이미지를 첨부하는 방식으로 가야할 것 같습니다.**

**Comment by cbnuleehyunwoo** [comment]
기존 방법에 비하여 다른 문제가 확인되지 않는다면 더 좋은 방법인 것 같습니다. 우선 저도 코드 구현을 진행할 때 이렇게 진행하겠습니다.

**Comment by gihong-free** [comment]
저도 앞으로의 수행에서는 이러한 방법으로 구현하겠습니다. 기존의 코드들은 수정하겠습니다.
