### ISSUE TITLE
css/js 파일 적용 방법

### ISSUE THREAD

**Issue by choigowon** [cbnuLeehyunwoo/Fine_Dust_Measurment#27]
다운받은 이미지를 첨부하는 방법과 유사하게 static 파일 안에 css 파일을 만들어서 그 안에 css파일을 넣어주시면 됩니다.

예)
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/154347680/9248edef-9055-43b3-abd6-2a2f89b03d13)

이후 html에
`<link href="{{url_for('static', filename='css/style.css')}}" rel="stylesheet">`
이렇게 작성해주시면 됩니다.

>  js도 마찬가지!

**Comment by choigowon** [comment]
단 이것은 파이썬 파일을 실행했을 때만 적용됩니다.

만약 html만 실행시킬 경우는 css 파일이 연동되지 않습니다.

**Comment by gihong-free** [comment]
말씀하신대로 html만 실행하는 경우에는 위의 방식이 아닌 보편적인 css문법을 그냥 쓰면 될 것 같습니다.
파이썬과 html울 둘 다 사용하는 현우님이 참고하면 좋을 것 같습니다.

**Comment by cbnuleehyunwoo** [comment]
넵 감사합니다 코드 구현할 때 참고하도록 하겠습니다
