### ISSUE TITLE
미세먼지 행동요령 만들기

### ISSUE THREAD

**Issue by gihong-free** [cbnuLeehyunwoo/Fine_Dust_Measurment#28]
미세먼지 예보기준을 기존에 정했습니다. 이에 따른 행동 요령을 작성해주시면 감사하겠습니다.

**Comment by choigowon** [comment]
환기 - 주의
가벼운운동(러닝) - 주의
과격운동(등산, 축구 등) - 양호
실외수업 - 주의
가벼운 외출 - 나쁨
마스크, 보호안경 쓰기 - 나쁨
피크닉 - 주의
가급적 실내활동 - 나쁨
외출금지 - 외출금지
코 세척 - 양호
야외 바베큐 - 주의
일광건조 - 양호
바둑, 장기 - 양호
체력측정 - 양호

**Comment by cbnuLeehyunwoo** [comment]
<html xmlns="http://www.w3.org/TR/REC-html40" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word"><head><title></title></head><body>
  | 좋음(0~30) | 양호(31~50) | 주의(51~70) | 나쁨(71~85) | 매우나쁨(86~100) | 외출금지(101~
-- | -- | -- | -- | -- | -- | --

환기 | 가능 | 가능 | 가능 | 불가능 | 불가능 | 불가능

가벼운운동 | 가능 | 가능 | 가능 | 불가능 | 불가능 | 불가능

과격한운동 | 가능 | 가능 | 불가능 | 불가능 | 불가능 | 불가능

실외수업 | 가능 | 가능 | 가능 | 불가능 | 불가능 | 불가능

가벼운 외출 | 가능 | 가능 | 가능 | 가능 | 불가능 | 불가능

마스크 보호안경쓰기 |   |   |   |   | 권장 | 권장

피크닉 | 가능 | 가능 | 가능 | 불가능 | 불가능 | 불가능

가급적 실내활동 |   |   |   | 권장 | 권장 | 권장

외출금지 |   |   |   |   |   | 권장

코 세척 |   | 권장 | 권장 | 권장 | 권장 | 권장

야외 바베큐 | 가능 | 가능 | 가능 | 불가능 | 불가능 | 불가능

일광 건조 | 가능 | 가능 | 불가능 | 불가능 | 불가능 | 불가능

바둑, 장기 | 가능 | 가능 | 불가능 | 불가능 | 불가능 | 불가능

체력 측정 | 가능 | 가능 | 불가능 | 불가능 | 불가능 | 불가능


</body></html>

**Comment by cbnuleehyunwoo** [comment]
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/85469621/13e37b3b-e6ef-45e4-a821-330e9d078b3d)
엑셀 표로 옮겨보았습니다. 나중에 구현할 때 참고하시면 좋을 것 같습니다.
추가적으로 색칠된 부분은 나중에  민감군을 고려하여 출력하는 기능을 추가할 때 가능을 불가능으로, 빈칸을 권장으로 바꾸면 될것 같습니다

**Comment by gihong-free** [comment]
미세먼지 행동요령 작성에 활용하겠습니다. 감사합니다.
