### ISSUE TITLE
미세먼지 각 지역별 행동요령 출력 디자인 제안

### ISSUE THREAD

**Issue by cbnuleehyunwoo** [cbnuLeehyunwoo/Fine_Dust_Measurment#29]
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/85469621/84ef18d7-a5cc-45f5-a491-3357396bc817)

미세먼지 측정기의 지역별 행동요령을 어떻게 출력할지 생각해 보았습니다. 해당 디자인을 기초로 개선해 나가면 될 것 같습니다.

**Comment by gihong-free** [comment]
고생하셨습니다. 해당 초안을 토대로 구현해보겠습니다.

**Comment by cbnuleehyunwoo** [comment]
행동요령 같은 경우에는 양이 많아 다른페이지에 구현해야할 수도 있을 것 같습니다.
