### ISSUE TITLE
미세먼지 예보기준 정하기

### ISSUE THREAD

**Issue by cbnuleehyunwoo** [cbnuLeehyunwoo/Fine_Dust_Measurment#3]
미세먼지의 예보기준을 어떻게 정할지 정하면 좋을 것 같습니다. 
해당 이슈는 급하게 생각하지 않고 천천히 생각하는 것이 좋을 것 같습니다.
  우선 생각해볼 것은 크게 두 가지가 있습니다.

1. 예보 단계 이름 정하기 
현재 대한민국은 좋음, 보통, 나쁨, 매우 나쁨 등으로 구분이 되고 있는데 이러한 단계 작명법에 따라서 단계를 늘리거나 줄이는 것도 괜찮을 것 같고,  혹은 이러한 작명이 현재 정도에 권장되거나 권장되지 않는 행동(ex 외출, 야외 러닝, 환기) 등이 잘 연상되지 않는 아쉬움이 있는 것 같습니다.  이러한 점을 생각하여 예보의 단계를 정해도 될 것 같습니다. 

2. 각 예보 단계 구분 기준
현재 우리나라는 pm(㎍/㎥)단위기준 좋음 0-30 보통 31-80 나쁨 81-150 매우 나쁨 151-  등의 기준을 세우고 있고  저희만의 기준을 세울지 혹은 이를 따를지 생각해봐야 할 것 같습니다.

**Comment by choigowon** [comment]
저는 현재 '좋음~매우 나쁨'의 기준을 그대로 유지하면서 각 단계 별 권장 지침 정도만 추가하면 될 것 같습니다.

혹시나 세분화하게 되더라도 '좋음'과 '보통'은 크게 권장되는 지침은 없으니 '나쁨'과 '매우 나쁨' 단계의 기준을 세분화 하면 좋을 것 같습니다.

**Comment by choigowon** [comment]
WHO 에서는 8단계로 나뉘어져 있어 여길 참고하면 될 것 같습니다.

**Comment by gihong-free** [comment]
![미세먼지 행동요령](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/81912071/a41e3acc-b07e-4495-a8c1-3f4090d6a05b)
위와 같은 행동 요령을 참고하여 사용자에게 와닿는 기준을 정하면 될 것 같습니다.

**Comment by cbnuleehyunwoo** [comment]
위의 내용들을 고려하여 6단계로 나누어 보았습니다. 

1. 좋음
0 ~ 30
2. 양호
31 ~ 50
3. 주의
51 ~ 70
4. 나쁨
71 ~ 85
5. 매우나쁨
86 ~ 100
6. 외출금지
101~
위를 기준으로 계속 수정해보면 될 것 같습니다.
