### ISSUE TITLE
각 창 별로 제공하는 정보

### ISSUE THREAD

**Issue by choigowon** [cbnuLeehyunwoo/Fine_Dust_Measurment#30]
처음 도시 선택 창에서 도시를 선택하면 새로운 창을 띄워 정보를 제공하고 있습니다.
우리가 제공할 정보는 미세먼지 웹 스크래핑값 / 아두이노 측정값, 행동요령 등이 있습니다.
어느 창에서 어떤 정보를 제공할 지 정확히 정해야 그에 맞게 코드를 작성할 수 있습니다.

예) 행동요령을 처음 페이지에서 보여줄 건지, 미세먼지 값이랑 같이 보여줄 건지
아두이노 측정값을 스크래핑 값이랑 같이 보여줄 건지, 새로 창을 열어서 보여줄 건지 등

**Comment by gihong-free** [comment]
제가 구상 중인 것인 초반에 행동요령 칸을 따로 만드는 것입니다. 그 외의 말씀하신 부분들은 각자 구현 중인 부분이라 한 번 모여서 논의하는 것이 좋아보입니다.

**Comment by choigowon** [comment]
행동 요령은 첫 번째 페이지 보다는 결과 페이지랑 같이 뜨면 좋을 것 같습니다.
