### ISSUE TITLE
아두이노 측정 값을 사용자에게 어떻게 전달할지 논의

### ISSUE THREAD

**Issue by cbnuleehyunwoo** [cbnuLeehyunwoo/Fine_Dust_Measurment#32]
아두이노 값이 기존의 스크래핑한 값과 비교하였을 때 센서의 정밀도, 혹은 측정 위치가 상이하여 값이 튀는 경우가 많은 것 같습니다. 이러한 상황일 때 아두이노 값과 기존 값들을 어떻게 처리하여 사용자에게 전달할지 논의가 필요할 것 같습니다.

**Comment by gihong-free** [comment]
웹 스크래핑을 통해 얻은 미세먼지 데이터들을 주로 가져가고, 아두이노를 이용한 미세먼지 수치는 서브 느낌으로 가져가야할 것 같습니다. 아직은 두리뭉실하게 말씀 드릴 수 없을 것 같습니다. 추후에 논의를 통해 정해야 하는 부분인 것 같습니다.

**Comment by choigowon** [comment]
아두이노 값을 띄우는 창을 새로 하나 만들어서 저희가 추천해주는 사이트의 값이랑 비교해서 보여주는 것이 나을 듯합니다.
