### ISSUE TITLE
현재 진행 상황 및 논의

### ISSUE THREAD

**Issue by gihong-free** [cbnuLeehyunwoo/Fine_Dust_Measurment#34]
현재 저희는 분업을 통해 웹 구현을 하고 있고, 어느정도 완성 단계에 도달했기에 이제는 각자가 만든 것과 앞으로 어떻게 만들 것인지 서로가 알아야 다음 것을 만들 단계에 온 것 같습니다. 따라서 현재 자신이 어디까지 구현했는지 작성해 주시고 따로 만나 논의를 하면 좋을 것 같습니다. 
 아래에 현재 구현 상태를 적어주세요.

**Comment by gihong-free** [comment]
저는 현재 웹 사이트 첫 화면에서 미세먼지 단계와 행동요령을 어떻게 구현할 지 고민 중입니다.

**Comment by gihong-free** [comment]
저는 현재 웹 사이트 첫 번째 화면을 어느정도 마무리한 상태입니다.

**Comment by choigowon** [comment]
아두이노와 유사한 값의 사이트를 추천해줍니다.

**Comment by cbnuleehyunwoo** [comment]
우선 현재 값에 따라 행동요령을 출력해주는 html,css, javascript 코드를 짜고있습니다.
