### ISSUE TITLE
웹 사이트 제목 추천 받습니다.

### ISSUE THREAD

**Issue by gihong-free** [cbnuLeehyunwoo/Fine_Dust_Measurment#36]
처음에 임의로 '미세먼지 측정기'라고 작성했는데, 아무래도 구현을 하니 완성도가 떨어져 보입니다. 프로젝트의 제목이자 간판인 만큼 우리의 주제를 잘 담은 제목이 필요해 보입니다.
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/81912071/07ad0864-8714-4173-8389-b4560dd78513)

**Comment by choigowon** [comment]
다나와 미세먼지

**Comment by gihong-free** [comment]
미세먼지 알리미로 하겠습니다
