### ISSUE TITLE
serial 라이브러리를 설치하여도 'model serial has no attribute Serial' 오류가 출력되는 이슈

### ISSUE THREAD

**Issue by cbnuleehyunwoo** [cbnuLeehyunwoo/Fine_Dust_Measurment#37]
새로운 개발환경에서 scr.py 파일을 실행하려고 할 때 pip3 install serial을 입력하여 설치하였음에도 불구하고 'model serial has no attribute Serial' 라는 오류가 출력되는 버그가 발생하였습니다. 이에 대해 구글링해본 결과

pip3 uninstall serial
pip3 install pyserial

을 수행해주시면 해결이 됩니다.
혹 해당현상을 겪고 해결방안을 입력했음에도 문제해결이 되지 않으면 알려주시기 바랍니다.

**Comment by choigowon** [comment]
아두이노 값도 정상적으로 출력되나요?

**Comment by cbnuleehyunwoo** [comment]
네 정상적으로 출력됩니다,
