### ISSUE TITLE
5/18일 회의> 못구한 사진들 같이 구해주세요

### ISSUE THREAD

**Issue by cbnuleehyunwoo** [cbnuLeehyunwoo/Fine_Dust_Measurment#39]
조깅 가능

마스크, 보호안경 쓰기 권장

가급적 실내활동 권장

코 세척 권장

야외 바베큐 가능

야외 바베큐 불가능 

일광 건조 가능

일광 건조 불가능

바둑, 장기 가능

바둑, 장기 불가능

체력 측정 가능

체력 측정 불가능

실외 수업 가능

실외 수업 불가능

피크닉 가능

피크닉 불가능

가벼운 운동 가능

가벼운 운동 불가능

과격한 운동 가능

과격한 운동 불가능

가벼운 외출 가능

가벼운 외출 불가능

![329965569-13e37b3b-e6ef-45e4-a821-330e9d078b3d](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/85469621/250a9a10-01f4-4bbb-bffc-bb231ff24f13)

**Comment by cbnuLeehyunwoo** [comment]
제가 조깅 부터 일광건조까지 찾아보도록 하겠습니다.

**Comment by cbnuleehyunwoo** [comment]
제가 조깅 부터 일광건조까지 찾아보도록 하겠습니다. 
조깅 가능https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExNmdyMTBlODE4eGNjYTBsNXRuMGk2OXA1OG4zdGU4OWJrODBxMnVoZyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/xT5LMu002LiWzUrRyE/giphy.

마스크 및 보호안경 쓰기
https://jjalbang.today/files/jjalbox/2022/05/20220526_628f38289566a.gif
가급적 실내활동
https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExcHlpcjIyb20yazB4ZWUyenZ5b3Q0cG4xMTdjNGE4eG02enRqaHhhaSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/N1n3RFwTVXWM0Dpj3d/giphy.gif

코세척
https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExOTZxdG85ZzByZ3hyN3o2d3FkZXVwdmFrbm4xeThkYjk0cmdheDVlMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3otPovr6LMRg5avWmY/giphy.gif

바베큐 가능
https://media2.giphy.com/media/TiVdW8hqXSRducil5X/giphy.webp?cid=790b7611sc4dbaxy41r6ibc9qrs5gxd0mgfk9b57rh1abexq&ep=v1_gifs_search&rid=giphy.webp&ct=g

바베큐 불가능
https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExNTdsNzBlemZrdXl5NXpycmxpYTJtdzk2b3JiNnd1bnV6eTgwcmJjdSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/OMeGDxdAsMPzW/giphy.gif

일광건조 가능
https://media1.giphy.com/media/ln4bohPvHhwgo/giphy.webp?cid=ecf05e47b83xdt4t7689xz2v55n8ulk3vvt53w9wloz5w47b&ep=v1_gifs_search&rid=giphy.webp&ct=g

일광건조 불가능

**Comment by choigowon** [comment]
가벼운 운동 가능
https://media1.giphy.com/media/3ohs7J1ZmzXZmj5o6A/giphy.gif?cid=790b7611ayplbpnwhhf9ydpha8qxb72czgo2cmubcwfar4l9&ep=v1_gifs_search&rid=giphy.gif&ct=g

가벼운 운동 불가능
https://i.namu.wiki/i/FgRvYsirraMEiQVb582pfenhZBYTUC6m4N4eQbzHOwr09jUKZMkbRhry-t4jHDUw9sPOCKfRWCgu6ubeBU2GmQ.gif

과격한 운동 가능
https://cdn.dribbble.com/users/31664/screenshots/1892284/media/b646cbd223213d7af78f302d5af30037.gif
https://media0.giphy.com/media/1itbXhSnMBkYEztiMQ/giphy.gif?cid=6c09b952qeodelop0p4il88dt71d7yp2unnzaihz0nl8rirc&ep=v1_gifs_search&rid=giphy.gif&ct=g

과격한 운동 불가능
https://i.namu.wiki/i/9sG4fMliwczY79a_2CLzV8xNv19GJGzVG-QEiHDHOm_ncSpocfzR_Gl-zuvZMdZCqMZWumA8ztlZblWzvqVHkw.gif

가벼운 외출 가능
https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAxOTA0MThfMjUy%2FMDAxNTU1NTc1NjU1NDMz.srUhbqiRAi7E0Q_YCpuRrDnSbzwsJTHdzOdQspy3_3Ag.Q3ApRQ89V16KPBZXyIYjLyQbEwpdcXB369opSDHe7xEg.GIF.sswnsdn%2F1.gif&type=sc960_832_gif
https://media4.giphy.com/media/5b7MblUbiHwDxm35nj/giphy.gif?cid=6c09b95230tn7mwmxq1cps0rfso668etui9wmt6azo3u5w0p&ep=v1_internal_gif_by_id&rid=giphy.gif&ct=g

가벼운 외출 불가능

**Comment by gihong-free** [comment]
바둑, 장기 가능
https://thumbnews.nateimg.co.kr/view610///news.nateimg.co.kr/orgImg/jo/2023/01/10/1d01a6a6-0a61-459d-be16-e7155c6d3b9d.jpg
바둑, 장기 불가능

체력 측정 가능
https://media0.giphy.com/media/QsyISIeqbKZ5q4bMpj/200.webp?cid=ecf05e47738xgbj29nehbcza0nvoym1to64bopa1kogf8x5w&ep=v1_gifs_search&rid=200.webp&ct=g
체력 측정 불가능
https://i2.ruliweb.com/ori/19/06/13/16b4cfdbcc74f7ae6.mp4?gif
실외 수업 가능
https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcREK0aZfhv3Q7I-MnYrAgCJN4rcabkoJz4b0RYBA1yRbw&s
실외 수업 불가능

피크닉 가능
https://media4.giphy.com/media/3o6Mbo5EtSpALmSrGo/200.webp?cid=790b7611f5cfw4zmvb7ckz2p59nvpgnv45x0wdg66egh3kj3&ep=v1_gifs_search&rid=200.webp&ct=g
피크닉 불가능
https://media1.giphy.com/media/3o6Mb7psCHBmY5XICA/200.webp?cid=ecf05e47phe4uhfohkg3xnb6shb0956zql42w7fq2vsq3d77&ep=v1_gifs_search&rid=200.webp&ct=g

**Comment by gihong-free** [comment]
체력측정 가능
https://media0.giphy.com/media/QsyISIeqbKZ5q4bMpj/200.webp?cid=ecf05e47738xgbj29nehbcza0nvoym1to64bopa1kogf8x5w&ep=v1_gifs_search&rid=200.webp&ct=g

피크닉 가능
https://media4.giphy.com/media/3o6Mbo5EtSpALmSrGo/200.webp?cid=790b7611f5cfw4zmvb7ckz2p59nvpgnv45x0wdg66egh3kj3&ep=v1_gifs_search&rid=200.webp&ct=g

피크닉 불가능
https://media1.giphy.com/media/3o6Mb7psCHBmY5XICA/200.webp?cid=ecf05e47phe4uhfohkg3xnb6shb0956zql42w7fq2vsq3d77&ep=v1_gifs_search&rid=200.webp&ct=g
