### ISSUE TITLE
사이트 추가 기능 추천

### ISSUE THREAD

**Issue by gihong-free** [cbnuLeehyunwoo/Fine_Dust_Measurment#41]
![스크린샷 2024-05-18 201054](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/81912071/88e41f75-2b8b-4fd1-bcac-14f78e7b7b88)
위의 오른쪽 구석의 공백에 추가할 기능 추천 받습니다.

**Comment by gihong-free** [comment]
저는 저희 사이트가 제공하고 있는 기능들을 간략하고 보기 좋게 보여주는 것도 좋을 것 같습니다.

**Comment by gihong-free** [comment]
![스크린샷 2024-05-18 205525](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/81912071/856e20a0-589a-4580-b92a-6a009e3e681c)
저희의 사이트 기능 혹은 차별성을 작성할 초안입니다.

**Comment by cbnuleehyunwoo** [comment]
제 생각에도 남는 여백에는 저희 사이트가 제공하는 기능들을 간략히 설명해주는게 좋은것 같습니다

**Comment by choigowon** [comment]
이후에도 공간이 남는다면 미세먼지에 대한 정의(위험성)를 넣으면 어떨까요

**Comment by gihong-free** [comment]
참고하겠습니다. 감사합니다.
