### ISSUE TITLE
웹사이트 폰트 논의 

### ISSUE THREAD

**Issue by cbnuleehyunwoo** [cbnuLeehyunwoo/Fine_Dust_Measurment#43]
css 파일을 작성하는 중 폰트의 결정에 어려움을 겪고 있습니다. 혹시 저희 웹사이트에 알맞는 폰트 디자인 및 설정에 대한 아이디어가 있으시면 해당 아이디어로 통일하면 좋을 것 같습니다.

**Comment by choigowon** [comment]
어느 창 디자인을 말씀하시는 건가요?

**Comment by cbnuleehyunwoo** [comment]
우선 행동요령을 띄워주는 창의 폰트 디자인을 고민하고 있었는데 아무래도 웹사이트의  전체 폰트를 통일하는게 좋지 않을까 합니다. 괜찮은 폰트 디자인이 있으면  알려주시고 다들 해당 폰트를 사용하는 방향이 어떤가 합니다.

**Comment by gihong-free** [comment]
폰트 적용하는 방식이 생각보다 까다로운 것으로 알고 있어서 공부하고 말씀드리겠습니다.
