### ISSUE TITLE
결과창 추가할 정보

### ISSUE THREAD

**Issue by choigowon** [cbnuLeehyunwoo/Fine_Dust_Measurment#44]
현재 결과창 디자인을 거의 마무리한 상태입니다.
추가로 보여줄 정보를 제안받습니다.
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/154347680/7a8df962-93db-483d-b382-0f4eb7932a0e)

**Comment by cbnuleehyunwoo** [comment]
제 생각은  추천값을 출력하는 창이 더 커지면 좋을 것 같습니다.

**Comment by gihong-free** [comment]
현우님의 미세먼지 행동요령을 추가하고도 공간이 남는다면 미세먼지의 위험성에 대해 작성해도 좋을 것 같습니다.
