### ISSUE TITLE
아두이노 결과값 정보 제공 방법

### ISSUE THREAD

**Issue by choigowon** [cbnuLeehyunwoo/Fine_Dust_Measurment#45]
아두이노 측정값은 우리가 있는 장소에서밖에 정보 제공이 가능합니다. 즉, 모든 지역에 아두이노 결과값을 제공할 수 없습니다.
따라서 아두이노 기기를 가지고 있는 사용자가 직접 아두이노 측정값을 구할 수 있도록 해야할 것 같습니다.

이에 따라 아두이노 기기를 연결하여 측정하는 방법에 대한 설명이 추가되어야 할 것 같습니다.

**Comment by gihong-free** [comment]
READ.ME에 추가해 주시면 감사하겠습니다.

**Comment by cbnuleehyunwoo** [comment]
좋은 생각이신것 같습니다 제가 아두이노 부분을 담당하였으니 리드미 부분에 추가하도록 하겠습니다.
