### ISSUE TITLE
현재 master branch 실행 방법

### ISSUE THREAD

**Issue by choigowon** [cbnuLeehyunwoo/Fine_Dust_Measurment#47]
scr.py에 아두이노 추천값을 제공하는 함수가 추가되었습니다.
아두이노 기기값이 측정값이 없으면 해당 함수가 정상적으로 작동되지 않습니다.
따라서 이후에 코드 수정이 있기 전까지는 임의의 정수값을 넣어주시기 바랍니다.
(현재 master 브랜치를 그대로 실행하는 경우)

**Comment by choigowon** [comment]
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/154347680/cac8cb2d-843a-4e18-92ea-cd71f2aa3c92)

해당 함수의 `ard=read_arduino()` 부분을 'ard=임의의 정수값'으로 바꿔주셔야 작동이 가능합니다.

**Comment by gihong-free** [comment]
참고하겠습니다. 감사합니다.
