### ISSUE TITLE
사이트 기능 이미지 필요

### ISSUE THREAD

**Issue by gihong-free** [cbnuLeehyunwoo/Fine_Dust_Measurment#51]
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/81912071/be1f4ebc-c837-4ce8-a70a-d044a12f547b)

위의 사진과 같이 저희 사이트의 기능들을 추가해야 합니다.
1. 실시간 미세먼지 스크래핑 이미지
2.  아두이노 미세먼지 측정 이미지
3.  미세먼지 행동요령

위의 사진들을 첨부해 주시면 감사하겠습니다.

**Comment by cbnuleehyunwoo** [comment]
행동요령 부분은 제가 작업을 마치는대로 올리도록 하겠습니다

**Comment by choigowon** [comment]
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/154347680/a61b5971-27ca-4b67-8680-a152af221b29)

**Comment by gihong-free** [comment]
참고하겠습니다.
