### ISSUE TITLE
아두이노 데이터를 한번 수신하면 다시 업데이트되지 않던 문제 수정

### ISSUE THREAD

**Issue by cbnuleehyunwoo** [cbnuLeehyunwoo/Fine_Dust_Measurment#55]
문제 상황: 무한반복문을 사용하고있었지만 아두이노 데이터를 한번 수신했음에도 데이터가 해당 값에서 고정되어 새로 불러올 수 없었음

문제 해결: 파이썬의 threading 모듈을 이용하여 아두이노 데이터를 읽어오는 작업을 독립적으로 수행
수정 후
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/85469621/99c73294-a534-4ed8-b6ba-68620b6389a9)
해당 출력은 불필요하기에 평소에는 주석처리해두었다가  필요할 때 사용하면 될 것 같습니다.

**Comment by gihong-free** [comment]
고생하셨습니다

**Comment by choigowon** [comment]
어떤 경우에서 해당 코드가 필요한가요?

**Comment by cbnuleehyunwoo** [comment]
> 어떤 경우에서 해당 코드가 필요한가요?

아두이노를 파이썬과 연결하게 되면 아두이노의 시리얼 모니터를 사용할 수 없어서 출력값을 실시간으로 확인할 수 없기 때문에 
1. 아두이노 값이 파이썬과 실시간으로 잘 연결되는지 확인.
2.  파이썬에서 미세먼지 센서에 오류가 없는지 확인할 때 
등의 상황에서 사용하면 될 것 같습니다.
