### ISSUE TITLE
행동요령 창 작업 결과물 검토 바랍니다.

### ISSUE THREAD

**Issue by cbnuleehyunwoo** [cbnuLeehyunwoo/Fine_Dust_Measurment#56]
현재 행동요령을 표시해주는 창의 작업을 마친 상태입니다. 팀원 분들이 모아주신 사진 덕분에 수월하게 작업할 수 있었습니다. 

링크가 깨지거나 한 사진들이 있어서 올려주신 사진 외에 다른 사진을 사용한 부분도 있으니 확인해주시고
행동요령과 맞지 않다고 생각하는 사진이 있거나 혹시 다른 추가했으면 좋은 사진이나 행동요령이 있으시면 댓글로 적어주시면 감사하겠습니다.
좋음(0 - 30)
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/85469621/5f68e71f-e9b6-4db7-bc66-e44340618f6a)

양호(31 - 50)
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/85469621/be249a5e-91ff-4041-a229-f7ac0448c602)

주의(51 - 70)
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/85469621/1aff2f96-a7d8-4c07-a780-e303c4b12a87)

나쁨(71 - 85)
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/85469621/0dec9e6f-1e42-46b5-9283-176800179db8)

매우나쁨(86 - 100)
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/85469621/cc134e4c-3ee5-4b65-9066-42e08118a446)

외출금지(101- )
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/85469621/51722b26-0a60-4dc5-97df-99ab596ea6e1)

의견들을 종합 후 수정하여 머지리퀘스트 올리도록 하겠습니다.

**Comment by gihong-free** [comment]
아무래도 위의 행동요령을 띄우는 사이트를 당담하고 있는 고원님의 의견이 중요해 보입니다.
저는 좋은 것 같습니다^~^

**Comment by choigowon** [comment]
가능한 행동이랑 불가능한 행동이랑 구분하는 건 어떨까요?

**Comment by cbnuleehyunwoo** [comment]
저도 가능과 불가능을 구분하는 것이 가독성 부분에서 좋을 것 같다고 생각합니다.  시간이 날때 수정해보도록 하겠습니다.
