### ISSUE TITLE
행동요령 결과창

### ISSUE THREAD

**Issue by choigowon** [cbnuLeehyunwoo/Fine_Dust_Measurment#57]
행동요령 main 브랜치에 merge되면 결과창에 같이 뜨도록 하겠습니다.
혹시나 행동요령을 다른 창에 띄운다던가하는 다른 의견 있으면 comment 달아주시기 바랍니다.
![제목 없음](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/154347680/9b022085-74db-46e9-bcca-a2f1d06b0a33)

**Comment by cbnuleehyunwoo** [comment]
정보를 한눈에 볼 수 있어서 좋은 생각이신 것 같습니다.
