### ISSUE TITLE
사이트별 도시 선택 문제

### ISSUE THREAD

**Issue by choigowon** [cbnuLeehyunwoo/Fine_Dust_Measurment#6]
현재 네이버 / 웨더아이 / 충북 보건소에서 웹 스크래핑을 받아 온 상태입니다.
사이트 별로 제공하는 도시 구분이 각자 달라서 위치를 지정하는 데 어려움이 있습니다.

예를 들어 '청주'를 검색해보면 네이버는 청주로 지정되고, 웨더아이는 읍/면/동으로 구분하여 검색 결과가 나오지 않고, 보건소는 청주의 읍/면/동을 모두 보여주게 됩니다.

어떻게 위치를 지정해야 할지 의견 부탁드립니다.

![스크린샷 2024-04-13 003337](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/154347680/03b757b0-5c59-40af-89c5-1af487eb1738)
![스크린샷 2024-04-13 003515](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/154347680/bee1294f-6242-44f1-b574-46dd0275b722)
![스크린샷 2024-04-13 003542](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/154347680/7180b6af-ae3a-4fff-a677-41cec84757d7)
![스크린샷 2024-04-13 003623](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/154347680/1ef0c499-8ccd-4f85-82c7-ad9ef4623ab9)

**Comment by gihong-free** [comment]
사이트 구현 과정에서 읍/면/동까지 넣게 되면 너무 많은 구현이 필요합니다.
따라서 당장은 시까지만 하는 것이 좋아 보입니다.

**Comment by choigowon** [comment]
그렇다고 시까지만 하기에는 너무 적어보여서 구현하는데 어려움이 있더라도 저는 읍/면/동까지 나타내야 한다고 봅니다.

**Comment by cbnuleehyunwoo** [comment]
그러면 우선 충청북도의 다른 도시는 시까지만 구현한 후  청주시는 4개의 구까지 구현하고 여유가 되면 더 세부적으로 구현하는 방법은 어떠신가요?

**Comment by choigowon** [comment]
네 그럼 일단 그렇게 수정해보겠습니다.

**Comment by gihong-free** [comment]
그러면 최종적으로 현우님의 의견에 따라 우선 충청북도의 다른 도시는 시까지만 구현한 후 청주시는 4개의 구까지 구현하고 여유가 되면 더 세부적으로 구현하도록 하겠습니다.
