### ISSUE TITLE
미세먼지 관련 설명 팝업 추가

### ISSUE THREAD

**Issue by gihong-free** [cbnuLeehyunwoo/Fine_Dust_Measurment#60]
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/81912071/149d97ad-6378-4b2e-9834-72240e0370ec)
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/81912071/0e7123f0-d5ef-49a2-a7f0-b580c15ecd0a)
위와와 같이 설명에 따른 버튼 클릭 시 팝업창에 설명이 나오도록 설정했습니다.

**Comment by cbnuleehyunwoo** [comment]
고생하셨습니다. 저희 웹사이트에 필요한 기능인 것 같습니다

**Comment by choigowon** [comment]
저도 필요한 기능이라고 생각합니다.

개인적인 의견으로는 화면이 왼쪽보다 오른쪽에 좀 치우처져 있어서 약간의 위치 조정을 하는건 어떤가요?

**Comment by gihong-free** [comment]
참고하겠습니다
