### ISSUE TITLE
아두이노 미세먼지 측정기 초기 전압 측정 

### ISSUE THREAD

**Issue by cbnuleehyunwoo** [cbnuLeehyunwoo/Fine_Dust_Measurment#62]
현재 저희가 사용하는 미세먼지 측정기는  저울로 무게를 잴 때 값을 리셋하듯이 '초기전압'을 측정하고 제외해주어야 보다 정확한 값을 얻을 수 있습니다.  초기 전압을 측정하는 방법은 센서에 미세먼지가 감지되지 않을 때의 전압을 여러 번 측정하여 평균을 구해주면 되겠습니다. 
가장 좋은 방법은 공기청정기 위에 센서를 올려놓고 측정하는 방법이 좋을 방법이지만 여건 상의 이유로 저는  미세먼지 센서 측정기의 구멍한쪽을 테이프로 막아놓고 센서 내의 먼지가 가라앉기를 기다렸다가 전압을 측정하는 방법을 사용하도록 하겠습니다.
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/85469621/ef6b377d-6d4f-4500-9ab3-2518026fe0dc)

**Comment by choigowon** [comment]
그렇게 하면 측정하는데 시간이 얼마나 걸리죠?

**Comment by cbnuleehyunwoo** [comment]
이번 주 중에는 마무리가 될 것 같습니다.
