### ISSUE TITLE
지역 선택 버튼

### ISSUE THREAD

**Issue by choigowon** [cbnuLeehyunwoo/Fine_Dust_Measurment#64]
현재 원모양의 버튼을 선택하여 지역을 선택하고 있는데, 지역 모양에 맞춰 선택하는 걸로 디자인 변경이 가능한가요?
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/154347680/9450eaa5-2783-48ae-9045-8d7debf700b4)

**Comment by gihong-free** [comment]
검토해보겠습니다.
