### ISSUE TITLE
디자인 추천

### ISSUE THREAD

**Issue by choigowon** [cbnuLeehyunwoo/Fine_Dust_Measurment#69]
디자인 변경해봤습니다. 어떤 디자인이 더 나은지 알려주세요.
어느 것의 어느 부분이 더 좋은 것 같다 자세하게 알려주시면 더 좋습니다!

**Comment by choigowon** [comment]
이전 이미지
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/154347680/6b1ad2ae-965e-41a3-a6ed-e34816fc8a52)

**Comment by choigowon** [comment]
변경 디자인
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/154347680/45f0726e-3162-471b-b199-08f25dc1af06)

**Comment by cbnuleehyunwoo** [comment]
변경 디자인이 뭔가 좀더 깔끔한 느낌이 있는것 같습니다.

**Comment by gihong-free** [comment]
저도 변경 후가 더 좋은 것 같습니다
