### ISSUE TITLE
지역 선택 시 새 창 뜨게 해주세요

### ISSUE THREAD

**Issue by choigowon** [cbnuLeehyunwoo/Fine_Dust_Measurment#7]
python의 각 지역 별 결과를 html에 나타내기 위해 지역 선택할 때마다 새 창 띄우도록 코드 작성해주세요.
@gihong-free

**Comment by choigowon** [comment]
python에서 Flask 웹 프레임워크를 이용하여 연동하는 방법이 있습니다.

**Comment by choigowon** [comment]
python에서 Flask 웹 프레임워크를 이용하여 html을 불러오는 방법이 있습니다.

from flask import Flask, render_template

app = Flask(__name__)

@app.route('/')
def index():
    return render_template('mygoogle.html')

if __name__ == '__main__':
    app.run(debug=True)

다음과 같은 코드를 이용하여 python에서 html 문서를 불러오는 데까지 성공하였습니다.

**Comment by gihong-free** [comment]
지역 선택 시 새 창을 뜨도록 '청주' 버튼에 기능 추가했습니다. 
제가 구현한 기능이 마음에 들면 다른 버튼들도 위와 같은 기능을 추가하겠습니다.
