### ISSUE TITLE
아두이노 설명서 위치 추천

### ISSUE THREAD

**Issue by cbnuleehyunwoo** [cbnuLeehyunwoo/Fine_Dust_Measurment#70]
사용자가 아두이노 키트를 조립하여 설정할 수 있게 하는 가이드를 어디에 위치할지 고민중입니다.

1. 리드미 파일에 추가.

2. html파일의 형태로 만들어 사이트에 추가.

제 생각에는 사이트에 배치하는 것이 사용자들에게 접근성이 좋을 것 같다고 생각하는데 팀원 분들의 생각을 공유해주시면 감사하겠습니다.

**Comment by choigowon** [comment]
저는 사이트에 추가하는게 좋을 것 같습니다!

**Comment by gihong-free** [comment]
그렇다면 사이트 쪽에 아두이노 설명 공간을 마련해 보겠습니다

**Comment by cbnuleehyunwoo** [comment]
의견 감사합니다!
