### ISSUE TITLE
화면 확대 및 축소 시 블록 크기 고정

### ISSUE THREAD

**Issue by choigowon** [cbnuLeehyunwoo/Fine_Dust_Measurment#73]
화면을 확대나 축소할 때마다 블록이 따라서 크기가 변합니다. 확대나 축소할 일이 없더라도 모니터마다 화면 크기가 달라 모니터에 따라 보이는 화면이 달라질 수 있기 때문에 블록 크기를 고정할 필요가 있을 것 같습니다. 해결 방안을 알려주시면 감사하겠습니다.

**Comment by choigowon** [comment]
축소 시
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/154347680/b2828808-37c5-4147-94f5-c270f30e1b39)

**Comment by choigowon** [comment]
확대 시
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/154347680/f1d110bd-243a-4a2f-a13e-61f140719dfc)

**Comment by cbnuleehyunwoo** [comment]
css파일에서 높이와 너비 픽셀로 설정하는 방법이 있을 것 같습니다.

**Comment by choigowon** [comment]
`width:00px;` 너비 크기 지정 후 `margin:auto;`로 가운데 정렬하여 크기 및 위치 고정하였습니다.
확대 및 축소하여도 블록이 고정되는 걸 확인하였습니다.

- 확대
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/154347680/30c096e6-b651-4850-a0ef-2415f724fc39)

- 축소
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/154347680/805b4477-3745-48a4-b2d2-7340717a4645)
