### ISSUE TITLE
행동요령 결과창 글씨출력 제안

### ISSUE THREAD

**Issue by cbnuleehyunwoo** [cbnuLeehyunwoo/Fine_Dust_Measurment#74]
이전에 각 미세먼지 상황별 행동요령을 출력하는 html, css를 짜서 넣었었는데 다시 검토해보니 가능 불가능, 권장을 사용자가 바로 인식하기에 조금 부족하다는 생각이 들었습니다. 
-가능, 불가능, 권장에 색깔 추가
-가능, 불가능, 권장 끼리 배열하기 
등을 적용하면 더욱 나아질 것 같습니다. 
지금 고원님이 행동요령과 결과창을 합치는 작업을 하고 계신데 해당 작업이 끝나면 제가 위에 설명드린 작업을 수행하겠습니다.

**Comment by choigowon** [comment]
머지요청하였습니다. 작업하시면 될 것 같습니다.

**Comment by choigowon** [comment]
가능은 파란색 불가능은 빨간색 어떨까요?

**Comment by cbnuleehyunwoo** [comment]
앗 일단 가능 초록 권장 파랑 불가능 빨강으로 해놓긴 했는데 뭔가 가능과 권장 색깔 정하는게 애매한 것 같습니다. 이에 대해 이슈 한번 올려보도록 하겠습니다..
