### ISSUE TITLE
아두이노 설명란 크기에 따른 사이트 창 크기 변화

### ISSUE THREAD

**Issue by gihong-free** [cbnuLeehyunwoo/Fine_Dust_Measurment#78]
![스크린샷 2024-05-25 183733](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/81912071/01a41c30-0542-40da-bd00-aed928635637)
위처럼 아두이노 설명창의 폭에 따라 사이트의 설명란도 같이 변경되는 문제가 있습니다.

**Comment by gihong-free** [comment]
아마 css 그리드 쪽에 문제가 있는 것 같은데 해결방안 알려주시면 감사하겠습니다.

**Comment by cbnuleehyunwoo** [comment]
저도 여백을 해결하는데 있어 어려움을 많이 겪고있어 구체적인 해결방법을 잘 모르겠네요 ㅠ  이번주에 한번 만나서 같이 해결해보는 것도 좋을 것 같습니다.
