### ISSUE TITLE
사이트 디자인 변경

### ISSUE THREAD

**Issue by gihong-free** [cbnuLeehyunwoo/Fine_Dust_Measurment#79]
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/81912071/dcf6d835-c5cd-4b6f-b722-0febbb1fcd29)
변경 전
![스크린샷 2024-05-25 193448](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/81912071/73642d2f-e51c-41d9-ad33-38031518c39f)
변경 후

**Comment by gihong-free** [comment]
어느 것이 더 나은 것 같나요?

**Comment by cbnuleehyunwoo** [comment]
변경 후가 확실히 잘 정리된 느낌이 있는 것 같습니다.
