### ISSUE TITLE
아두이노 측정기 초기세팅 메뉴얼 

### ISSUE THREAD

**Issue by cbnuleehyunwoo** [cbnuLeehyunwoo/Fine_Dust_Measurment#84]
아두이노 측정기 초기세팅 메뉴얼을 만들어 보았습니다. 필요한 부분만 넣었다고 생각했는데 생각보다 긴 것 같네요 

미세먼지 측정기 세팅방법
1. 위에 나와있는 대로 회로도를 연결해 주세요.
2. 미세먼지 센서를 먼지가 없는 곳(공기청정기 위)에 두거나 테이프를 이용하여 구멍을 막아주세요.
3. ArduinoIDE를 설치해주시고 설치가 완료되면 아두이노를 USB를 통해 연결해주세요
4. ArduinoIDE에서 도구(Tools)->포트(Port)항목에 진입하여 연결된 포트를 확인해주세요
5. ArduinoIDE를 이용하여check_defaultV.ino 파일을 아두이노 우노에 업로드 해주세요. 
6. 아두이노 개발환경의 도구(Tools)->시리얼 모니터(Serial Monitor)로 들어가 출력값이 뜨는지 확인해 주세요.
7. 충분한 시간동안(최소 10분) 동안 값을 측정해주세요. 
8. 출력된 평균값을 read_Dust.ino 파일의 18번째 줄 "defaultV =" 오른쪽에 넣어주세요(기존값은 지워주세요).
9. ArduinoIDE를 이용하여 read_Dust.ino 파일을 아두이노 우노에 업로드 해주세요.
10. 마지막으로 scr.py 파일에 들어가서 3번에서 확인했던 포트번호를 12번째 줄 "PORT ="오른쪽에 넣어주세요(기존값은 지워주세요)
주의사항: scr.py 파일을 실행하실 때 시리얼 모니터가 켜져있지 않게해주세요.(값 출력이 안됩니다.)

혹시 추가할 부분이 있거나 피드백을 주실분은 주시면 감사하겠습니다. 
또한 해당 부분을
1. html파일에만 추가
2. html, readme 파일 둘 다 추가 
할지 의견을 알려주시면 감사하겠습니다.

**Comment by choigowon** [comment]
생각보다 제약이 많은데 현재로써는 이게 최선이죠?

**Comment by cbnuleehyunwoo** [comment]
네 필수적인 것만 넣는다고 넣었는데 아무래도 길긴 한 것 같습니다. 설명을 좀 더 간소화할 수 있으면 간소화 해보겠습니다.
