### ISSUE TITLE
아두이노 초기세팅 페이지 디자인 결과 및 위치 논의

### ISSUE THREAD

**Issue by cbnuleehyunwoo** [cbnuLeehyunwoo/Fine_Dust_Measurment#85]
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/85469621/f4f739af-5ffa-46ac-b405-e61f398cdc7e)
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/85469621/3ec03ca4-173f-4ae8-a7f0-ce2bbe0f391a)
초기세팅을 설명하는 페이지 구현이 대강 완료되었습니다. 혹시 구현 내용에 대한 피드백이 있으시면 알려주시고
해당 페이지를
1. 메인 페이지
2. 결과창 페이지
3. 별도의 창으로 띄우기
중 어느 위치에 놓을지도 의견을 주시면 감사할 것 같습니다!

**Comment by choigowon** [comment]
결과창에 설명보기 버튼을 누르면 작은 창이 뜨도록 하는 건 어떨까요?

**Comment by cbnuleehyunwoo** [comment]
좋은 생각이신 것 같습니다 다만 내용이 좀 많아서 어떻게 표시될지 일단 구현해봐야할것 같습니다
