### ISSUE TITLE
Unittest를 위해 scr.py 파일 분할

### ISSUE THREAD

**Issue by choigowon** [cbnuLeehyunwoo/Fine_Dust_Measurment#86]
현재 scr.py 파일에 함수와 Flask 실행 코드가 모두 작성되어있습니다.
함수부분은 unittest 하는 데 문제가 없으나
Flask 실행 코드는 `if __name__ == '__main__':` 에 포함되어있어 오류가 발생하고 있습니다.
따라서 run.py 파일에 Flask 실행 코드를 scr.py 파일에 각종 함수를 작성하여 분할하였습니다.

**Comment by choigowon** [comment]
코드 수정 이후에도 정상적으로 작동하는 것을 확인하였습니다.
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/154347680/9daf7704-9377-40d8-a095-ddb927109044)

**Comment by choigowon** [comment]
혹시 이외에도 class 내부 함수나 변수에 접근하는 방법을 아시는 분은 comment 달아주세요

**Comment by cbnuLeehyunwoo** [comment]
수고하셨습니다 이번주 내로 만나서 유닛테스트 해보면 될것 같습니다
