### ISSUE TITLE
메뉴얼 버튼위치 논의

### ISSUE THREAD

**Issue by cbnuleehyunwoo** [cbnuLeehyunwoo/Fine_Dust_Measurment#87]
일단 결과창에 아두이노 세팅 메뉴얼을 링크해두려고 합니다. 그러던 중 버튼위치를 어디에 놓아야할지 많이 고민입니다. 팀원 여러분의 의견을 알려주시면 감사할 것 같습니다.
1안 
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/85469621/a514df5b-c771-4983-93dc-63b0d50919b5)

2안
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/85469621/9ba163da-6d5e-45aa-869f-ff704473e67c)

3안
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/85469621/52b1cc76-a277-47ce-ae4a-4926afc18b46)

제 생각에는 한줄에 때려넣는 것은 뭔가 난잡해보여서 2안이나 3안처럼 출력하는게 좋은 것 같습니다.

**Comment by choigowon** [comment]
3안이 괜찮아보이네요

**Comment by cbnuleehyunwoo** [comment]
의견 감사합니다. 우선 현재 코드에 3안이 적용되어있습니다.  마스터브랜치에 작업내용 머지리퀘스트 올리도록 하겠습니다.
