### ISSUE TITLE
Unittest - read_arduino() 함수 오류

### ISSUE THREAD

**Issue by choigowon** [cbnuLeehyunwoo/Fine_Dust_Measurment#88]
scr.py 파일 Unittest 진행 중입니다. 다른 함수들은 정상적으로 작동하는데 read_arduino() 함수에서 `ser = serial.Serial(PORT, BaudRate)` 부분에서 오류가 뜹니다. 아두이노 연결안되있어서 그런건지 진짜 오류인건지 잘 모르겠습니다.
일단 테스트는 잘 동작하는데 저 부분에서 계속 오류가 뜹니다. 해결 방안 알려주세요.

> Exception in thread Thread-1 (read_arduino):
Traceback (most recent call last):
  File "c:\Users\최고원\Desktop\오픈소스\project\practice\scr.py", line 12, in read_arduino
    ser = serial.Serial(PORT, BaudRate)
     .     ^^^
Ran 1 test in 0.001s^^^
OK^^
^

**Comment by cbnuleehyunwoo** [comment]
아마 제 생각에도 연결이 안되어있어서 그런 것 같습니다. 해당 부분은 제가 테스트 하도록 하겠습니다!

**Comment by choigowon** [comment]
연결이 안되어있을 경우 `from unittest.mock import patch, MagicMock` 라이브러리를 import 한 후
- 직렬 포트를 모의로 설정: 테스트는 `unittest.mock`을 사용하여 `serial.Serial`을 모의 객체로 대체
- 모의 설정: 모의 직렬 포트는 데이터가 있음을 시뮬레이션하기 위해 `(in_waiting = True)` 설정되고, `readline` 메서드가 호출될 때 특정 값 `('123.45\n')`을 반환하도록 설정
- 읽기 스레드 시작: 테스트는 `read_arduino()`를 실행하는 별도의 스레드를 시작
- 읽기 작업 대기: 메인 스레드는 읽기 작업이 완료될 시간을 확보하기 위해 1초 동안 대기
이 접근 방식은 실제 하드웨어 없이도 `read_arduino()`의 동작을 검증할 수 있게 하여, 함수가 모의 데이터를 올바르게 처리

**Comment by choigowon** [comment]
해당 코드
```
@patch('serial.Serial')
    def test_arduino_data_number(self, mock_serial):
        # mock 객체 설정
        mock_serial_instance = MagicMock()
        mock_serial.return_value = mock_serial_instance
        mock_serial_instance.in_waiting = True
        mock_serial_instance.readline.return_value = b'123.45\n'
        
        # 스레드 시작
        scr.threading.Thread(target=scr.read_arduino, daemon=True).start()
        
        # 스레드가 값을 읽을 시간을 줌
        scr.threading.Event().wait(1)
```

**Comment by choigowon** [comment]
오류없이 테스트 작동하였습니다.
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/154347680/bdd737c9-a826-480a-9a81-b499a49a7cc6)
