### ISSUE TITLE
최종 사이트 기능 별 사진 요청

### ISSUE THREAD

**Issue by gihong-free** [cbnuLeehyunwoo/Fine_Dust_Measurment#92]
최종 결과물인 웹 스크래핑, 아두이노 측정 결과창, 미세먼지 행동요령 이미지를 올려주시면 감사하겠습니다.

**Comment by choigowon** [comment]
결과창입니다.
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/154347680/2ab4b78e-d470-4e2b-8bb0-548cd0fc377f)

**Comment by gihong-free** [comment]
![스크린샷 2024-06-01 210559](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/81912071/d24a10a2-d022-4b39-833b-6f992597415b)

**Comment by gihong-free** [comment]
![스크린샷 2024-06-01 220358](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/81912071/ebfce3fc-667c-4086-8715-8bf0bbfeee81)

**Comment by gihong-free** [comment]
![KakaoTalk_20240601_220922853](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/81912071/0266e6cd-58b6-4251-92f0-6fed97887f71)
