### ISSUE TITLE
최종 사이트

### ISSUE THREAD

**Issue by gihong-free** [cbnuLeehyunwoo/Fine_Dust_Measurment#94]
![스크린샷 2024-06-01 222232](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/81912071/41940fa7-8756-4709-b7ff-b6fc21f14101)

**Comment by gihong-free** [comment]
최종 구현 사진입니다.

**Comment by choigowon** [comment]
사진 깨짐, 제목 가운데 정렬 문제로 인해 코드 수정하였습니다.
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/154347680/d45ab137-e51e-46c4-9c1d-4b53e3344be8)
결과창 상단이랑 디자인을 맞췄는데 디자인에 대한 의견있으면 반영하겠습니다.
