### ISSUE TITLE
site.html 사진 오류

### ISSUE THREAD

**Issue by choigowon** [cbnuLeehyunwoo/Fine_Dust_Measurment#95]
![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/154347680/a9c1421c-5d46-4c31-8110-656f3c194a45)
사진이 뜨지 않습니다.

![image](https://github.com/cbnuLeehyunwoo/Fine_Dust_Measurment/assets/154347680/714ce249-6e94-416c-8471-b31b170b6cc5)
부가 설명창 사진은 정상적으로 뜹니다.

**Comment by gihong-free** [comment]
아무래도 깃허브에 사진을 올려서 생긴 오류같습니다.
제 생각에는 위의 사이트 부분은 이미지 주소가 아닌 이미지로 하는 것이 좋아 보입니다.

**Comment by gihong-free** [comment]
이미지 파일을 넣어서 수정 후, pull request 요청드렸습니다.

**Comment by choigowon** [comment]
사진 확인하였습니다.
다만 Flask 실행하면서 경로가 달라져 경로까지 수정하니 정상적으로 뜨는 것을 확인하였습니다.
